open module sdr.trunk {
    exports com.sun.java.swing.plaf.windows to jide.oss;
    exports io.github.dsheirer.audio.codec.mbe.decrypt;
    exports io.github.dsheirer.bits;
    exports io.github.dsheirer.edac;
    exports io.github.dsheirer.preference.encryption;
    exports io.github.dsheirer.preference.portable;

    uses io.github.dsheirer.audio.codec.mbe.decrypt.VoiceDecryptionModule;

    requires JTransforms;
    requires ch.qos.logback.classic;
    requires ch.qos.logback.core;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.dataformat.xml;
    requires com.fazecast.jSerialComm;
    requires com.formdev.flatlaf;
    requires com.formdev.flatlaf.intellijthemes;
    requires com.google.common;
    requires com.google.gson;
    requires com.miglayout.swing;
    requires commons.math3;
    requires io.github.dsheirer.rrapi;
    requires java.desktop;
    requires java.management;
    requires java.net.http;
    requires java.prefs;
    requires java.sql;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires javafx.swing;
    requires jdk.httpserver;
    requires jdk.incubator.vector;
    requires jdk.management;
    requires jiconfont;
    requires jiconfont.font.awesome;
    requires jiconfont.javafx;
    requires jiconfont.swing;
    requires jide.oss;
    requires jmbe.api;
    requires lame;
    requires libresample4j.master;
    requires mina.core;
    requires mina.http;
    requires mp3agic;
    requires org.apache.commons.csv;
    requires org.apache.commons.io;
    requires org.apache.commons.lang3;
    requires org.controlsfx.controls;
    requires org.slf4j;
    requires org.xerial.sqlitejdbc;
    requires usb.api;
    requires usb4java;
}
