/*
 * *****************************************************************************
 * Copyright (C) 2014-2024 Dennis Sheirer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * ****************************************************************************
 */
package io.github.dsheirer.edac;

import io.github.dsheirer.bits.BinaryMessage;
import io.github.dsheirer.bits.CorrectedBinaryMessage;

/**
 * P25 CRC check/correction methods
 */
public class CRCP25
{
    private static final int CCITT_MESSAGE_LENGTH = 80;
    private static final int CCITT_CRC_LENGTH = 16;
    private static final int CRC_9_LENGTH = 9;
    private static final int CRC_32_LENGTH = 32;
    private static final long CRC_16_POLYNOMIAL = 0x1021L;
    private static final long CRC_9_POLYNOMIAL = 0x59L;
    private static final long CRC_32_POLYNOMIAL = 0x04C11DB7L;
    private static final long CRC_16_INVERSION = 0xFFFFL;
    private static final long CRC_9_INVERSION = 0x1FFL;
    private static final long CRC_32_INVERSION = 0xFFFFFFFFL;
    private static final int[] CCITT_80_SYNDROMES = createCCITT80Syndromes();

    private CRCP25()
    {
    }

    /**
     * Creates the single-bit syndromes for the 80 data bits followed by the 16 CRC bits in a P25 header or TSBK.
     * The CRC bits are transmitted most-significant bit first.
     */
    private static int[] createCCITT80Syndromes()
    {
        int[] syndromes = new int[CCITT_MESSAGE_LENGTH + CCITT_CRC_LENGTH];

        for(int bit = 0; bit < CCITT_MESSAGE_LENGTH; bit++)
        {
            int remainder = 1;

            for(int shift = 0; shift < CCITT_CRC_LENGTH + CCITT_MESSAGE_LENGTH - bit - 1; shift++)
            {
                boolean highBit = (remainder & 0x8000) != 0;
                remainder = (remainder << 1) & 0xFFFF;

                if(highBit)
                {
                    remainder ^= (int)CRC_16_POLYNOMIAL;
                }
            }

            syndromes[bit] = remainder;
        }

        for(int bit = 0; bit < CCITT_CRC_LENGTH; bit++)
        {
            syndromes[CCITT_MESSAGE_LENGTH + bit] = 1 << (CCITT_CRC_LENGTH - bit - 1);
        }

        return syndromes;
    }

    /**
     * CRC-12 checksums for P25 Phase 2 MAC PDU Contents.  This is used for a 144-bit message and 12-bits of checksum
     * using a polynomial of 0x1897 and generated by:
     * <p>
     * long[] checksums = CRCUtil.generate(144, 12, 0x1897l, 0x0l, false);
     */
    private static int[] CRC_12_FACCH = new int[]{0x256, 0x12B, 0xCDE, 0x66F, 0xF7C, 0x7BE, 0x3DF, 0xDA4, 0x6D2, 0x369,
            0xDFF, 0xAB4, 0x55A, 0x2AD, 0xD1D, 0xAC5, 0x929, 0x8DF, 0x824, 0x412, 0x209, 0xD4F, 0xAEC, 0x576, 0x2BB,
            0xD16, 0x68B, 0xF0E, 0x787, 0xF88, 0x7C4, 0x3E2, 0x1F1, 0xCB3, 0xA12, 0x509, 0xECF, 0xB2C, 0x596, 0x2CB,
            0xD2E, 0x697, 0xF00, 0x780, 0x3C0, 0x1E0, 0xF0, 0x78, 0x3C, 0x1E, 0xF, 0xC4C, 0x626, 0x313, 0xDC2, 0x6E1,
            0xF3B, 0xBD6, 0x5EB, 0xEBE, 0x75F, 0xFE4, 0x7F2, 0x3F9, 0xDB7, 0xA90, 0x548, 0x2A4, 0x152, 0xA9, 0xC1F,
            0xA44, 0x522, 0x291, 0xD03, 0xACA, 0x565, 0xEF9, 0xB37, 0x9D0, 0x4E8, 0x274, 0x13A, 0x9D, 0xC05, 0xA49,
            0x96F, 0x8FC, 0x47E, 0x23F, 0xD54, 0x6AA, 0x355, 0xDE1, 0xABB, 0x916, 0x48B, 0xE0E, 0x707, 0xFC8, 0x7E4,
            0x3F2, 0x1F9, 0xCB7, 0xA10, 0x508, 0x284, 0x142, 0xA1, 0xC1B, 0xA46, 0x523, 0xEDA, 0x76D, 0xFFD, 0xBB5,
            0x991, 0x883, 0x80A, 0x405, 0xE49, 0xB6F, 0x9FC, 0x4FE, 0x27F, 0xD74, 0x6BA, 0x35D, 0xDE5, 0xAB9, 0x917,
            0x8C0, 0x460, 0x230, 0x118, 0x8C, 0x46, 0x23, 0xC5A, 0x62D, 0xF5D, 0xBE5, 0x9B9, 0x897};

    /**
     * CRC-12 checksums for P25 Phase 2 MAC PDU Contents.  This is used for a 168-bit message and 12-bits of checksum
     * using a polynomial of 0x1897 and generated by:
     * <p>
     * long[] checksums = CRCUtil.generate(168, 12, 0x1897l, 0x0l, false);
     */
    private static int[] CRC_12_SACCH = new int[]{0x47B, 0xE76, 0x73B, 0xFD6, 0x7EB, 0xFBE, 0x7DF, 0xFA4, 0x7D2, 0x3E9,
            0xDBF, 0xA94, 0x54A, 0x2A5, 0xD19, 0xAC7, 0x928, 0x494, 0x24A, 0x125, 0xCD9, 0xA27, 0x958, 0x4AC, 0x256,
            0x12B, 0xCDE, 0x66F, 0xF7C, 0x7BE, 0x3DF, 0xDA4, 0x6D2, 0x369, 0xDFF, 0xAB4, 0x55A, 0x2AD, 0xD1D, 0xAC5,
            0x929, 0x8DF, 0x824, 0x412, 0x209, 0xD4F, 0xAEC, 0x576, 0x2BB, 0xD16, 0x68B, 0xF0E, 0x787, 0xF88, 0x7C4,
            0x3E2, 0x1F1, 0xCB3, 0xA12, 0x509, 0xECF, 0xB2C, 0x596, 0x2CB, 0xD2E, 0x697, 0xF00, 0x780, 0x3C0, 0x1E0,
            0xF0, 0x78, 0x3C, 0x1E, 0xF, 0xC4C, 0x626, 0x313, 0xDC2, 0x6E1, 0xF3B, 0xBD6, 0x5EB, 0xEBE, 0x75F, 0xFE4,
            0x7F2, 0x3F9, 0xDB7, 0xA90, 0x548, 0x2A4, 0x152, 0xA9, 0xC1F, 0xA44, 0x522, 0x291, 0xD03, 0xACA, 0x565,
            0xEF9, 0xB37, 0x9D0, 0x4E8, 0x274, 0x13A, 0x9D, 0xC05, 0xA49, 0x96F, 0x8FC, 0x47E, 0x23F, 0xD54, 0x6AA,
            0x355, 0xDE1, 0xABB, 0x916, 0x48B, 0xE0E, 0x707, 0xFC8, 0x7E4, 0x3F2, 0x1F9, 0xCB7, 0xA10, 0x508, 0x284,
            0x142, 0xA1, 0xC1B, 0xA46, 0x523, 0xEDA, 0x76D, 0xFFD, 0xBB5, 0x991, 0x883, 0x80A, 0x405, 0xE49, 0xB6F,
            0x9FC, 0x4FE, 0x27F, 0xD74, 0x6BA, 0x35D, 0xDE5, 0xAB9, 0x917, 0x8C0, 0x460, 0x230, 0x118, 0x8C, 0x46, 0x23,
            0xC5A, 0x62D, 0xF5D, 0xBE5, 0x9B9, 0x897,};

    /**
     * CRC-16 checksums for P25 Phase 2 LCCH MAC PDU Contents.  This is used for a 164-bit message and 16-bits of
     * checksum using a polynomial of 0x11021 and generated by:
     * <p>
     * long[] checksums = CRCUtil.generate(164, 16, 0x11021l, 0x0l, true);
     */
    private static int[] CRC_16_LCCH = new int[]{0xCF76, 0x67BB, 0xBBCD, 0xD5F6, 0x6AFB, 0xBD6D, 0xD6A6, 0x6B53, 0xBDB9,
            0xD6CC, 0x6B66, 0x35B3, 0x92C9, 0xC174, 0x60BA, 0x305D, 0x903E, 0x481F, 0xAC1F, 0xDE1F, 0xE71F, 0xFB9F,
            0xF5DF, 0xF2FF, 0xF16F, 0xF0A7, 0xF043, 0xF031, 0xF008, 0x7804, 0x3C02, 0x1E01, 0x8710, 0x4388, 0x21C4,
            0x10E2, 0x871, 0x8C28, 0x4614, 0x230A, 0x1185, 0x80D2, 0x4069, 0xA824, 0x5412, 0x2A09, 0x9D14, 0x4E8A,
            0x2745, 0x9BB2, 0x4DD9, 0xAEFC, 0x577E, 0x2BBF, 0x9DCF, 0xC6F7, 0xEB6B, 0xFDA5, 0xF6C2, 0x7B61, 0xB5A0,
            0x5AD0, 0x2D68, 0x16B4, 0xB5A, 0x5AD, 0x8AC6, 0x4563, 0xAAA1, 0xDD40, 0x6EA0, 0x3750, 0x1BA8, 0xDD4, 0x6EA,
            0x375, 0x89AA, 0x44D5, 0xAA7A, 0x553D, 0xA28E, 0x5147, 0xA0B3, 0xD849, 0xE434, 0x721A, 0x390D, 0x9496,
            0x4A4B, 0xAD35, 0xDE8A, 0x6F45, 0xBFB2, 0x5FD9, 0xA7FC, 0x53FE, 0x29FF, 0x9CEF, 0xC667, 0xEB23, 0xFD81,
            0xF6D0, 0x7B68, 0x3DB4, 0x1EDA, 0xF6D, 0x8FA6, 0x47D3, 0xABF9, 0xDDEC, 0x6EF6, 0x377B, 0x93AD, 0xC1C6,
            0x60E3, 0xB861, 0xD420, 0x6A10, 0x3508, 0x1A84, 0xD42, 0x6A1, 0x8B40, 0x45A0, 0x22D0, 0x1168, 0x8B4, 0x45A,
            0x22D, 0x8906, 0x4483, 0xAA51, 0xDD38, 0x6E9C, 0x374E, 0x1BA7, 0x85C3, 0xCAF1, 0xED68, 0x76B4, 0x3B5A,
            0x1DAD, 0x86C6, 0x4363, 0xA9A1, 0xDCC0, 0x6E60, 0x3730, 0x1B98, 0xDCC, 0x6E6, 0x373, 0x89A9, 0xCCC4, 0x6662,
            0x3331, 0x9188, 0x48C4, 0x2462, 0x1231, 0x8108, 0x4084, 0x2042, 0x1021, 0x1, 0x2, 0x4, 0x8, 0x10, 0x20,
            0x40, 0x80, 0x100, 0x200, 0x400, 0x800, 0x1000, 0x2000, 0x4000, 0x8000};

    /**
     * Error detection and correction of single-bit errors for CCITT 16-bit
     * CRC protected 80-bit messages.
     */
    public static int correctCCITT80(CorrectedBinaryMessage message, int messageStart, int crcStart)
    {
        if(crcStart - messageStart != CCITT_MESSAGE_LENGTH || message.size() < crcStart + CCITT_CRC_LENGTH)
        {
            throw new IllegalArgumentException("P25 CRC-CCITT requires 80 data bits followed by 16 CRC bits");
        }

        int calculated = (int)calculateCRC(message, messageStart, crcStart, CCITT_CRC_LENGTH,
            CRC_16_POLYNOMIAL, CRC_16_INVERSION);
        int checksum = getIntChecksum(message, crcStart, CCITT_CRC_LENGTH);
        int residual = calculated ^ checksum;

        if(residual == 0)
        {
            return 0;
        }

        int errorLocation = getBitError(residual, CCITT_80_SYNDROMES);

        if(errorLocation >= 0)
        {
            message.flip(errorLocation + messageStart);
            message.incrementCorrectedBitCount(1);
            return 1;
        }

        //The residual isn't a correctable single-bit error.
        message.incrementCorrectedBitCount(2);

        return 2;
    }

    /**
     * Error detection for CRC-9 protected Confirmed Packet Data blocks.  The seven-bit block serial number and
     * 128 data bits are protected as one 135-bit value, while the transmitted CRC occupies bits 7-15 of the decoded
     * 144-bit block.  No data correction is performed.
     */
    public static CRC checkCRC9(BinaryMessage message, int messageStart)
    {
        if(message.size() < messageStart + 144)
        {
            return CRC.FAILED_CRC;
        }

        long remainder = calculateCRC(message, messageStart, messageStart + 7, CRC_9_LENGTH,
            CRC_9_POLYNOMIAL, 0);
        remainder = updateCRC(remainder, message, messageStart + 16, messageStart + 144, CRC_9_LENGTH,
            CRC_9_POLYNOMIAL);
        int calculated = (int)(remainder ^ CRC_9_INVERSION);
        int checksum = message.getInt(messageStart + 7, messageStart + 15);
        return calculated == checksum ? CRC.PASSED : CRC.FAILED_CRC;
    }

    /**
     * Checks the four-octet packet CRC defined by TIA-102.BAAA-A section 6.3.3.  The CRC covers all data and pad bits
     * before the CRC field and does not include the PDU header or confirmed-block sequence/CRC-9 fields.
     *
     * @param message containing the contiguous packet payload and CRC
     * @param messageStart first packet data bit
     * @param crcStart first bit of the transmitted 32-bit CRC
     * @return pass when the transmitted CRC exactly matches the specified inverted CRC
     */
    public static CRC checkCRC32(BinaryMessage message, int messageStart, int crcStart)
    {
        if(messageStart < 0 || crcStart <= messageStart || message.size() < crcStart + CRC_32_LENGTH)
        {
            return CRC.FAILED_CRC;
        }

        long calculated = calculateCRC(message, messageStart, crcStart, CRC_32_LENGTH, CRC_32_POLYNOMIAL,
            CRC_32_INVERSION);
        long checksum = getLongChecksum(message, crcStart, CRC_32_LENGTH);
        return calculated == checksum ? CRC.PASSED : CRC.FAILED_CRC;
    }

    /**
     * Calculates a direct, non-reflected CRC over the specified bit range.  Data is processed most-significant bit
     * first, matching the polynomial definitions in TIA-102.BAAA-A sections 6.2, 6.3.3, and 6.4.2.
     */
    private static long calculateCRC(BinaryMessage message, int messageStart, int messageEnd, int crcLength,
                                     long polynomial, long inversion)
    {
        return updateCRC(0, message, messageStart, messageEnd, crcLength, polynomial) ^ inversion;
    }

    private static long updateCRC(long remainder, BinaryMessage message, int messageStart, int messageEnd,
                                  int crcLength, long polynomial)
    {
        long highBit = 1L << (crcLength - 1);
        long mask = (1L << crcLength) - 1;

        for(int bit = messageStart; bit < messageEnd; bit++)
        {
            boolean feedback = ((remainder & highBit) != 0) ^ message.get(bit);
            remainder = (remainder << 1) & mask;

            if(feedback)
            {
                remainder ^= polynomial;
            }
        }

        return remainder;
    }


    /**
     * Performs extended Golay (24,12,8) error detection and correction against the 12
     * encoded 24-bit message segments following the 64-bit NID in the message
     *
     * @return - true if all 12 segments of the message can be checked/corrected
     */
    public static boolean correctGalois24(CorrectedBinaryMessage tdulc)
    {
        boolean passes = true;

        int x = 64;

        while(x < tdulc.size() && passes)
        {

            int errors = Golay24.checkAndCorrect(tdulc, x);

            passes = errors < 2;

            x += 24;
        }

        return passes;
    }

    /**
     * Calculates the CRC-12 checksum for the P25 Phase 2 MAC PDU Contents for S-OEMI/FACCH and compares it to the
     * transmitted checksum to verify that the message is correct.
     * Note: this uses the pre-calculated checksums in the CRC_12_FACCH array.
     *
     * @param message to verify
     * @return true if the message passes the CRC-12 check.
     */
    public static boolean crc12Facch(CorrectedBinaryMessage message)
    {
        int calculated = 0xFFF; //Initial fill of all ones.

        //Iterate the set bits and XOR the running checksum with pre-calculated lookup value
        for(int i = message.nextSetBit(0); i >= 0 && i < 144; i = message.nextSetBit(i + 1))
        {
            calculated ^= CRC_12_FACCH[i];
        }

        int checksum = message.getInt(144, 155); //12-bit transmitted checksum
        int residual = calculated ^ checksum;
        return residual == 0;
    }

    /**
     * Calculates the CRC-12 checksum for the P25 Phase 2 MAC PDU Contents for I-OEMI/SACCH and compares it to the
     * transmitted checksum to verify that the message is correct.
     * Note: this uses the pre-calculated checksums in the CRC_12_SACCH array.
     *
     * @param message to verify
     * @return true if the message passes the CRC-12 check.
     */
    public static boolean crc12Sacch(CorrectedBinaryMessage message)
    {
        int calculated = 0xFFF; //Initial fill of all ones.

        //Iterate the set bits and XOR the running checksum with pre-calculated lookup value
        for(int i = message.nextSetBit(0); i >= 0 && i < 168; i = message.nextSetBit(i + 1))
        {
            calculated ^= CRC_12_SACCH[i];
        }

        int checksum = message.getInt(168, 179); //12-bit transmitted checksum
        int residual = calculated ^ checksum;
        return residual == 0;
    }

    /**
     * Calculates the CRC-16 checksum for the P25 Phase 2 MAC PDU Contents for I-OECI/LCCH and compares it to the
     * transmitted checksum to verify that the message is correct.
     * Note: this uses the pre-calculated checksums in the CRC_16_LCCH array.
     *
     * @param message to verify
     * @return true if the message passes the CRC-16 check.
     */
    public static boolean crc16Lcch(CorrectedBinaryMessage message)
    {
        int calculated = 0xFFFF; //Initial fill of all ones.

        //Iterate the set bits and XOR the running checksum with pre-calculated lookup value
        for(int i = message.nextSetBit(0); i >= 0 && i < 164; i = message.nextSetBit(i + 1))
        {
            calculated ^= CRC_16_LCCH[i];
        }

        int checksum = message.getInt(164, 179); //16-bit transmitted checksum
        int residual = calculated ^ checksum;
        return residual == 0;
    }


    /**
     * Calculates the value of the message checksum as a long
     */
    public static long getLongChecksum(BinaryMessage message, int crcStart, int crcLength)
    {
        return message.getLong(crcStart, crcStart + crcLength - 1);
    }

    /**
     * Calculates the value of the message checksum as an integer
     */
    public static int getIntChecksum(BinaryMessage message, int crcStart, int crcLength)
    {
        return message.getInt(crcStart, crcStart + crcLength - 1);
    }

    /**
     * Identifies any single bit error position that matches the checksum error.
     */
    public static int getBitError(int checksumError, int[] checksums)
    {
        for(int x = 0; x < checksums.length; x++)
        {
            if(checksums[x] == checksumError)
            {
                return x;
            }
        }

        return -1;
    }
}
