/*
 * *****************************************************************************
 * Copyright (C) 2014-2024 Dennis Sheirer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * ****************************************************************************
 */

package io.github.dsheirer.edac;

import io.github.dsheirer.bits.BinaryMessage;
import io.github.dsheirer.bits.CorrectedBinaryMessage;
import java.util.Arrays;

/**
 * Extended Golay (24,12,8) decoder.
 */
public class Golay24
{
    private static final int UNCORRECTABLE = -1;

    private Golay24()
    {
    }

    /**
     * Golay 24/12 checksums generated by:
     *
     * CRCUtil.generate( 12, 11, 0xC75, 0x0, true );
     */
    private static final int[] CHECKSUMS = new int[]
            {
                    0x63A, 0x31D, 0x7B4, 0x3DA, 0x1ED, 0x6CC, 0x366, 0x1B3,
                    0x6E3, 0x54B, 0x49F, 0x475, 0x400, 0x200, 0x100, 0x080,
                    0x040, 0x020, 0x010, 0x008, 0x004, 0x002, 0x001
            };

    /**
     * Maps the 11-bit Golay syndrome plus the overall parity syndrome to the unique error pattern having a weight of
     * three or less.  The extended Golay code has a minimum distance of eight, so all patterns within its correction
     * radius have unique syndromes.  Entries that don't identify a correctable pattern remain {@link #UNCORRECTABLE}.
     */
    private static final int[] CORRECTION_PATTERNS = createCorrectionPatterns();

    private static int calculateChecksum(BinaryMessage message, int startIndex)
    {
        int calculated = 0; //Starting value

        /* Iterate the set bits and XOR running checksum with lookup value */
        for(int i = message.nextSetBit(startIndex);
            i >= startIndex && i < startIndex + 12;
            i = message.nextSetBit(i + 1))
        {
            calculated ^= CHECKSUMS[i - startIndex];
        }

        return calculated;
    }

    /**
     * Performs error detection and corrects the 24-bit codeword that starts at the start index in place.
     *
     * @param message - source message containing startIndex + 24 bits length
     * @param startIndex - start of the 24-bit Golay-protected bit set
     * @return 0 when the codeword is clean, 1 when it was corrected, or 2 when the errors are uncorrectable.  The
     * actual quantity of corrected bits is added to the message's corrected-bit count.
     */
    public static int checkAndCorrect(CorrectedBinaryMessage message, int startIndex)
    {
        if(startIndex < 0 || startIndex > message.size() - 24)
        {
            throw new IllegalArgumentException("A complete 24-bit Golay codeword must start within the message");
        }

        int syndrome = getSyndrome(message, startIndex);
        int syndromeAndParity = (syndrome << 1) | (hasOddParity(message, startIndex) ? 1 : 0);
        int correctionPattern = CORRECTION_PATTERNS[syndromeAndParity];

        if(correctionPattern == UNCORRECTABLE)
        {
            return 2;
        }

        int correctedBitCount = Integer.bitCount(correctionPattern);

        if(correctedBitCount == 0)
        {
            return 0;
        }

        int remainingCorrections = correctionPattern;

        while(remainingCorrections != 0)
        {
            int bitIndex = Integer.numberOfTrailingZeros(remainingCorrections);
            message.flip(startIndex + bitIndex);
            remainingCorrections &= remainingCorrections - 1;
        }

        message.incrementCorrectedBitCount(correctedBitCount);
        return 1;
    }

    private static boolean hasOddParity(BinaryMessage message, int startIndex)
    {
        boolean oddParity = false;
        int endIndex = startIndex + 24;

        for(int index = message.nextSetBit(startIndex);
            index >= startIndex && index < endIndex;
            index = message.nextSetBit(index + 1))
        {
            oddParity = !oddParity;
        }

        return oddParity;
    }

    private static int[] createCorrectionPatterns()
    {
        int[] correctionPatterns = new int[1 << 12];
        Arrays.fill(correctionPatterns, UNCORRECTABLE);
        registerCorrectionPattern(correctionPatterns, 0);

        for(int first = 0; first < 24; first++)
        {
            int firstBit = 1 << first;
            registerCorrectionPattern(correctionPatterns, firstBit);

            for(int second = first + 1; second < 24; second++)
            {
                int firstTwoBits = firstBit | (1 << second);
                registerCorrectionPattern(correctionPatterns, firstTwoBits);

                for(int third = second + 1; third < 24; third++)
                {
                    registerCorrectionPattern(correctionPatterns, firstTwoBits | (1 << third));
                }
            }
        }

        return correctionPatterns;
    }

    private static void registerCorrectionPattern(int[] correctionPatterns, int correctionPattern)
    {
        int syndrome = 0;
        int remainingCorrections = correctionPattern;

        while(remainingCorrections != 0)
        {
            int bitIndex = Integer.numberOfTrailingZeros(remainingCorrections);

            if(bitIndex < 23)
            {
                syndrome ^= CHECKSUMS[bitIndex];
            }

            remainingCorrections &= remainingCorrections - 1;
        }

        int syndromeAndParity = (syndrome << 1) | (Integer.bitCount(correctionPattern) & 1);

        if(correctionPatterns[syndromeAndParity] != UNCORRECTABLE)
        {
            throw new IllegalStateException("Duplicate correctable Golay syndrome");
        }

        correctionPatterns[syndromeAndParity] = correctionPattern;
    }

    private static int getSyndrome(BinaryMessage message, int startIndex)
    {
        int calculated = calculateChecksum(message, startIndex);

        int checksum = message.getInt(startIndex + 12, startIndex + 22);

        return (checksum ^ calculated);
    }
}
